In [50]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [51]:
data = pd.read_csv('/workspaces/ml/KNN/House Price Prediction Dataset (1).csv')
data

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [52]:
data = data.drop(['Id'], axis=1)
data

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3592,2,2,3,1938,Downtown,Good,No,266746
3,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...
1995,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1062,5,1,2,1903,Rural,Poor,No,476925
1998,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2989,5,1,3,1903,Suburban,Fair,No,482525

In [53]:
x =  data.drop(["Price", "Location", "Condition", "Garage"], axis=1)

In [54]:
y = data["Price"]

In [55]:
columns = data.columns
for col in columns:
    print(data[col].value_counts())
    print("\n")

Area
4219    5
1516    4
3691    4
1743    4
4646    4
       ..
647     1
4827    1
865     1
2174    1
4062    1
Name: count, Length: 1622, dtype: int64


Bedrooms
1    418
3    406
4    405
5    403
2    368
Name: count, dtype: int64


Bathrooms
3    524
4    521
2    494
1    461
Name: count, dtype: int64


Floors
2    691
1    661
3    648
Name: count, dtype: int64


YearBuilt
2005    27
2002    26
1901    25
1981    24
1938    23
        ..
1939    11
1944    10
1950     9
1994     7
2016     6
Name: count, Length: 124, dtype: int64


Location
Downtown    558
Urban       485
Suburban    483
Rural       474
Name: count, dtype: int64


Condition
Fair         521
Excellent    511
Poor         507
Good         461
Name: count, dtype: int64


Garage
No     1038
Yes     962
Name: count, dtype: int64


Price
959222    2
149919    1
424998    1
266746    1
244020    1
         ..
295620    1
580929    1
476925    1
161119    1
482525    1
Name: count, Length: 1999, dtype: int64

In [56]:
numerical  = ['Area','Bedrooms','Bathrooms','Floors', 'YearBuilt']

In [57]:
ct = ColumnTransformer(
    transformers = [("num", StandardScaler(), numerical)]
)

In [58]:
x_scaled = ct.fit_transform(x)

In [59]:
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size = 0.2, random_state = 32)

In [60]:
knnr = KNeighborsRegressor(n_neighbors = 550, metric = "euclidean")

In [61]:
knnr = KNeighborsRegressor(n_neighbors = 650, metric = "euclidean")
knnr.fit(X_train, Y_train)
pred = knnr.predict(X_test)
score = r2_score(Y_test, pred)
print(score)

-0.005279287000315103

In [62]:
pred = knnr.predict(X_test)

In [63]:
score = r2_score(Y_test, pred)

In [64]:
score

-0.005279287000315103