In [30]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.preprocessing import StandardScaler, OneHotEncoder
from sklearn.compose import ColumnTransformer
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsRegressor
from sklearn.metrics import r2_score, mean_squared_error

In [31]:
data = pd.read_csv(r"/workspaces/ml/KNN/House Price Prediction Dataset (1).csv")

In [32]:
data

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...,...
1995,1996,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,1997,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1998,1062,5,1,2,1903,Rural,Poor,No,476925
1998,1999,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2000,2989,5,1,3,1903,Suburban,Fair,No,482525

In [33]:
data.drop(["Id"],axis=1)

,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3592,2,2,3,1938,Downtown,Good,No,266746
3,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,4926,1,4,2,1975,Downtown,Fair,Yes,636056
...,...,...,...,...,...,...,...,...,...
1995,4994,5,4,3,1923,Suburban,Poor,No,295620
1996,3046,5,2,1,2019,Suburban,Poor,Yes,580929
1997,1062,5,1,2,1903,Rural,Poor,No,476925
1998,4062,3,1,2,1936,Urban,Excellent,Yes,161119
1999,2989,5,1,3,1903,Suburban,Fair,No,482525

In [41]:
x = data.drop(["Price"], axis=1)
x = data.drop(["Location", "Condition", "Garage"], axis=1)

In [35]:
y = data["Price"]

In [36]:
Columns = data.columns
for col in Columns:
    print(data[col].value_counts)
    print("\n")

<bound method IndexOpsMixin.value_counts of 0          1
1          2
2          3
3          4
4          5
        ...
1995    1996
1996    1997
1997    1998
1998    1999
1999    2000
Name: Id, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       1360
1       4272
2       3592
3        966
4       4926
        ...
1995    4994
1996    3046
1997    1062
1998    4062
1999    2989
Name: Area, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       5
1       5
2       2
3       4
4       1
       ..
1995    5
1996    5
1997    5
1998    3
1999    5
Name: Bedrooms, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       4
1       4
2       2
3       2
4       4
       ..
1995    4
1996    2
1997    1
1998    1
1999    1
Name: Bathrooms, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       3
1       3
2       3
3       2
4       2
       ..
1995    3
1996    1
1997    2
1998    2
1999    3
Name: Floors, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       1970
1       1958
2       1938
3       1902
4       1975
        ...
1995    1923
1996    2019
1997    1903
1998    1936
1999    1903
Name: YearBuilt, Length: 2000, dtype: int64>


<bound method IndexOpsMixin.value_counts of 0       Downtown
1       Downtown
2       Downtown
3       Suburban
4       Downtown
          ...
1995    Suburban
1996    Suburban
1997       Rural
1998       Urban
1999    Suburban
Name: Location, Length: 2000, dtype: str>


<bound method IndexOpsMixin.value_counts of 0       Excellent
1       Excellent
2            Good
3            Fair
4            Fair
          ...
1995         Poor
1996         Poor
1997         Poor
1998    Excellent
1999         Fair
Name: Condition, Length: 2000, dtype: str>


<bound method IndexOpsMixin.value_counts of 0        No
1        No
2        No
3       Yes
4       Yes
       ...
1995     No
1996    Yes
1997     No
1998    Yes
1999     No
Name: Garage, Length: 2000, dtype: str>


<bound method IndexOpsMixin.value_counts of 0       149919
1       424998
2       266746
3       244020
4       636056
         ...
1995    295620
1996    580929
1997    476925
1998    161119
1999    482525
Name: Price, Length: 2000, dtype: int64>

In [ ]:
numerical = ["Area", "Bedrooms", "Bathrooms", "Floors", "YearBuilt"]

In [44]:
col = ColumnTransformer(
    transformers=[("num", StandardScaler(), numerical)]
)

In [46]:
X_scaled = col.fit_transform(x)

In [47]:
X_train, X_test, Y_train, Y_test = train_test_split( x , y , test_size= 0.2 , random_state=32 )

In [48]:
knnr = KNeighborsRegressor(n_neighbors=550, metric="eclidean")

In [49]:
knnr = KNeighborsRegressor(n_neighbors = 650, metric = "euclidean")
knnr.fit(X_train, Y_train)
pred = knnr.predict(X_test)
score = r2_score(Y_test, pred)
print(score)

0.9280570258926465

In [50]:
pred = knnr.predict(X_test)

In [51]:
score = r2_score(Y_test, pred)
score

0.9280570258926465