In [1]:
import pandas as pd

In [4]:
data= pd.read_csv(r"/workspaces/ml/panda/Indian_Retail_Sales_Dataset.csv")
data

,Order ID,Order Date,Customer Name,State,Region,City,Category,Product Name,Quantity,Sales,Discount,Profit
0,1001,2025-12-13,Customer_35,Maharashtra,West,Pune,Electronics,Headphones,4,30256.0,0.05,4667.74
1,1002,2025-09-16,Customer_2,Maharashtra,West,Pune,Grocery,Sugar,1,1226.0,0.00,19.12
2,1003,2025-01-04,Customer_11,Rajasthan,North,Jaipur,Electronics,Smartwatch,4,59878.0,0.20,-1988.52
3,1004,2025-07-14,Customer_7,Uttar Pradesh,North,Lucknow,Furniture,Sofa,3,21915.0,0.10,-1154.27
4,1005,2025-07-13,Customer_6,Delhi,North,New Delhi,Furniture,Sofa,1,24161.5,0.15,1470.67
...,...,...,...,...,...,...,...,...,...,...,...,...
145,1146,2025-12-26,Customer_8,Uttar Pradesh,North,Lucknow,Grocery,Oil,8,134524.0,0.20,1667.17
146,1147,2025-08-21,Customer_26,Rajasthan,North,Jaipur,Grocery,Wheat,7,105325.5,0.05,6053.84
147,1148,2025-07-11,Customer_10,Uttar Pradesh,North,Lucknow,Grocery,Rice,6,85404.0,0.10,9923.86
148,1149,2025-07-10,Customer_9,West Bengal,East,Kolkata,Electronics,Laptop,2,6609.0,0.15,-469.44
149,1150,2025-08-05,Customer_4,Rajasthan,North,Jaipur,Electronics,Headphones,2,27422.0,0.10,4901.65

In [11]:
# 1

total_pro = data.groupby("State")[["Profit", "Sales"]].sum().reset_index()
total_pro
high = total_pro[total_pro["Sales"] > 10000]
high.sort_values(by="Sales",ascending=False).head(3)

         State     Profit      Sales
3  Maharashtra  133944.70  2054915.0
4    Rajasthan  111084.64  1524273.5
6    Telangana   64837.45  1072752.0

In [ ]:
# 2

orders = data.groupby("Customer Name")["Order ID"].count()
orders

Customer Name
Customer_1     5
Customer_10    4
Customer_11    6
Customer_12    2
Customer_13    4
Customer_14    2
Customer_15    4
Customer_16    7
Customer_17    5
Customer_18    4
Customer_19    7
Customer_2     4
Customer_20    3
Customer_21    8
Customer_22    3
Customer_23    3
Customer_24    3
Customer_25    7
Customer_26    1
Customer_27    2
Customer_28    7
Customer_29    5
Customer_3     4
Customer_30    4
Customer_31    5
Customer_32    6
Customer_33    3
Customer_34    3
Customer_35    5
Customer_4     3
Customer_5     6
Customer_6     5
Customer_7     3
Customer_8     2
Customer_9     5
Name: Order ID, dtype: int64